######################################################
#             CONFIG ANALOG OUTPUT SRV               #
######################################################

# OUTPUT_TYPE
int8 CURRENT = 0
int8 VOLTAGE = 1

int8       index    # output index
int8       type     # see OUTPUT_TYPE
---
bool       success