######################################################
#            CONFIG DISCRETE OUTPUT SRV              #
######################################################

# OUTPUT_RANGE
int8 RANGE_12V = 0
int8 RANGE_24V = 1

int8       index    # output index
int8       range    # see OUTPUT_RANGE
---
bool       success