######################################################
#            CONFIG QUADRATURE INPUT SRV             #
######################################################

int8       index            # input index (1 or 2)
int32      pulse_per_rev    # pulses per revolution (0 - 32767 LPR)
bool       idx_availability # index availability 
---
bool       success 