######################################################
#                GET ANALOG INPUT SRV                #
######################################################

int8       index    # input index
---
float32    value    
bool       success