######################################################
#              SET ANALOG OUTPUT SRV                 #
######################################################

int8       index     # output index
float32    value     # output value (various range)
---
bool       success