######################################################
#                   GET MASTER SPEED                 #
######################################################

---
float64    speed    # master speed (0 < speed <= 1)
bool       success