######################################################
#                  GET ROBOT STATE                   #
######################################################

---
RobotState  state    
bool        success