######################################################
#                  GET ROBOT MODE                    #
######################################################

---
RobotMode  mode    
bool       success