######################################################
#                  GET SAFETY ZONES                  #
######################################################

---
SafetyZone[]  zones  
bool          success