######################################################
#                  GET SAFETY MODE                   #
######################################################

---
SafetyMode  mode  
bool        success