######################################################
#                     LOG ALARM                      #
######################################################

---
SafetyEvent[]    safety_events  
bool             success