######################################################
#                 SET SYSTEM LOAD                    #
######################################################

# SUPPORTED_LOADS
string TOOLLOAD  = "toolload"
string PAYLOAD   = "payload"

string      name     # see SUPPORTED_LOADS
float64     mass
float64[3]  cog      # center of gravity - x, y, z [mm]
float64[6]  imx      # inertia matrix - xx, yy, zz, xy, xz, yz [kg/m2]
---
bool        success