######################################################
#                  PROGRAM RECOVERY                  #
######################################################

# SUPPORTED_ACTIONS
int8 RECOVER = 0
int8 SKIP    = 1

int8 action  # see SUPPORTED_ACTIONS
---
bool       success
