######################################################
#                  PAUSE MOTION                      #
######################################################

bool       blocking # wait until robot is stopped
---
bool       success