######################################################
#               SELECT JOGGING FRAME                 #
######################################################

# SUPPORTED_FRAMES
int8 WORLD = 0
int8 BASE  = 1
int8 TCP   = 2


int8       ref      # see SUPPORTED_FRAMES or use custom
---
bool       success