######################################################
#                 SET CUSTOM FRAME                   #
######################################################

int8       ref      # id - World(0), Base(1), TCP(2), Custom
float64[3] pos      # position - x, y, z [mm]
float64[3] rot      # orientation - r, p, y [degrees]
---
bool       success