######################################################
#                 SET INTERACTIVITY                  #
######################################################

bool       enable  
---
bool       success